baseURL = "https://forge.ocamlcore.org/"
languageCode = "en-us"
title = "OCaml Forge"
theme = "forge-theme"

[params]
  bugReportURL = "https://github.com/ocaml-forge/forge.ocamlcore.org/issues/new/choose"
  googleUA = "UA-44957583-2"
