name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check users/projects consistency
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the website
        run: make build
