name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check links.
      - uses: marccampbell/hugo-linkcheck-action@v0.1.3
        env:
          HUGO_FINAL_URL: https://forge.ocamlcore.org

      # Check consistency of users/projects.
      - name: Check users/projects consistency
        run: echo Hello, world!
