name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check links.
      - uses: actions/checkout@v2
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -r -v -d content content/*
      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}

      # Check consistency of users/projects.
      - name: Check users/projects consistency
        run: echo Hello, world!
